name: Check robots.txt

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

permissions:
  issues: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check robots.txt status
        run: |
          status=$(curl -s -o /dev/null -w "%{http_code}" https://www.williamnye.co.uk/robots.txt)
          if [ $status -ne 200 ]; then
            echo "robots.txt returned $status"
            exit 1
          fi

      - name: Post alert to Slack
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: |
              🚨 *robots.txt check failed*  
              The `robots.txt` file at <https://www.williamnye.co.uk/robots.txt> did not return a `200 OK` status code.  
              Status Code: $status  
              Please investigate the issue.

