name: Check robots.txt

on:
  schedule:
    - cron: '0 0 * * *'  # Every hour
  workflow_dispatch:

permissions:
  issues: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check robots.txt status
        id: check-status
        run: |
          status=$(curl -s -o /dev/null -w "%{http_code}" https://www.williamnye.co.uk/robots.txt)
          echo "HTTP status: $status"
          echo "status=$status" >> $GITHUB_ENV
          if [ "$status" -eq 200 ]; then
            echo "robots.txt is OK (status: $status). Exiting workflow."
            exit 0
          fi

      - name: Post alert to Slack
        if: always() && env.status != '200'
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: |
              🚨 *robots.txt check failed*  
              The `robots.txt` file at <https://www.williamnye.co.uk/robots.txt> did not return a `200 OK` status code.  
              Status Code: ${{ env.status }}  
              Please investigate the issue.
